// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: shared/proto/module.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_shared_proto_module_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_module_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_shared_proto_module_proto_rawDescGZIP(), []int{0}
}

type RegisterRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	StoreServerAddress string                 `protobuf:"bytes,1,opt,name=store_server_address,json=storeServerAddress,proto3" json:"store_server_address,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *RegisterRequest) Reset() {
	*x = RegisterRequest{}
	mi := &file_shared_proto_module_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterRequest) ProtoMessage() {}

func (x *RegisterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_module_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterRequest.ProtoReflect.Descriptor instead.
func (*RegisterRequest) Descriptor() ([]byte, []int) {
	return file_shared_proto_module_proto_rawDescGZIP(), []int{1}
}

func (x *RegisterRequest) GetStoreServerAddress() string {
	if x != nil {
		return x.StoreServerAddress
	}
	return ""
}

type RegisterResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Id            string                    `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                    `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Version       string                    `protobuf:"bytes,3,opt,name=version,proto3" json:"version,omitempty"`
	Routes        []*RegisterResponse_Route `protobuf:"bytes,4,rep,name=routes,proto3" json:"routes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse) Reset() {
	*x = RegisterResponse{}
	mi := &file_shared_proto_module_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse) ProtoMessage() {}

func (x *RegisterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_module_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse.ProtoReflect.Descriptor instead.
func (*RegisterResponse) Descriptor() ([]byte, []int) {
	return file_shared_proto_module_proto_rawDescGZIP(), []int{2}
}

func (x *RegisterResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *RegisterResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *RegisterResponse) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *RegisterResponse) GetRoutes() []*RegisterResponse_Route {
	if x != nil {
		return x.Routes
	}
	return nil
}

type Header struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Header        map[string]*Header_Value `protobuf:"bytes,1,rep,name=header,proto3" json:"header,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Header) Reset() {
	*x = Header{}
	mi := &file_shared_proto_module_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Header) ProtoMessage() {}

func (x *Header) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_module_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Header.ProtoReflect.Descriptor instead.
func (*Header) Descriptor() ([]byte, []int) {
	return file_shared_proto_module_proto_rawDescGZIP(), []int{3}
}

func (x *Header) GetHeader() map[string]*Header_Value {
	if x != nil {
		return x.Header
	}
	return nil
}

type Request struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Url           string                 `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	Header        *Header                `protobuf:"bytes,3,opt,name=header,proto3" json:"header,omitempty"`
	Body          []byte                 `protobuf:"bytes,4,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Request) Reset() {
	*x = Request{}
	mi := &file_shared_proto_module_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Request) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Request) ProtoMessage() {}

func (x *Request) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_module_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Request.ProtoReflect.Descriptor instead.
func (*Request) Descriptor() ([]byte, []int) {
	return file_shared_proto_module_proto_rawDescGZIP(), []int{4}
}

func (x *Request) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *Request) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *Request) GetHeader() *Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *Request) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

type Response struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Header        *Header                `protobuf:"bytes,2,opt,name=header,proto3" json:"header,omitempty"`
	Body          string                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Response) Reset() {
	*x = Response{}
	mi := &file_shared_proto_module_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Response) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Response) ProtoMessage() {}

func (x *Response) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_module_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Response.ProtoReflect.Descriptor instead.
func (*Response) Descriptor() ([]byte, []int) {
	return file_shared_proto_module_proto_rawDescGZIP(), []int{5}
}

func (x *Response) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *Response) GetHeader() *Header {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *Response) GetBody() string {
	if x != nil {
		return x.Body
	}
	return ""
}

type RegisterResponse_Route struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Method        string                 `protobuf:"bytes,1,opt,name=method,proto3" json:"method,omitempty"`
	Path          string                 `protobuf:"bytes,2,opt,name=path,proto3" json:"path,omitempty"`
	UseSse        bool                   `protobuf:"varint,3,opt,name=use_sse,json=useSse,proto3" json:"use_sse,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterResponse_Route) Reset() {
	*x = RegisterResponse_Route{}
	mi := &file_shared_proto_module_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterResponse_Route) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterResponse_Route) ProtoMessage() {}

func (x *RegisterResponse_Route) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_module_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterResponse_Route.ProtoReflect.Descriptor instead.
func (*RegisterResponse_Route) Descriptor() ([]byte, []int) {
	return file_shared_proto_module_proto_rawDescGZIP(), []int{2, 0}
}

func (x *RegisterResponse_Route) GetMethod() string {
	if x != nil {
		return x.Method
	}
	return ""
}

func (x *RegisterResponse_Route) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *RegisterResponse_Route) GetUseSse() bool {
	if x != nil {
		return x.UseSse
	}
	return false
}

type Header_Value struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []string               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Header_Value) Reset() {
	*x = Header_Value{}
	mi := &file_shared_proto_module_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Header_Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Header_Value) ProtoMessage() {}

func (x *Header_Value) ProtoReflect() protoreflect.Message {
	mi := &file_shared_proto_module_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Header_Value.ProtoReflect.Descriptor instead.
func (*Header_Value) Descriptor() ([]byte, []int) {
	return file_shared_proto_module_proto_rawDescGZIP(), []int{3, 0}
}

func (x *Header_Value) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

var File_shared_proto_module_proto protoreflect.FileDescriptor

const file_shared_proto_module_proto_rawDesc = "" +
	"\n" +
	"\x19shared/proto/module.proto\x12\x05proto\"\a\n" +
	"\x05Empty\"C\n" +
	"\x0fRegisterRequest\x120\n" +
	"\x14store_server_address\x18\x01 \x01(\tR\x12storeServerAddress\"\xd5\x01\n" +
	"\x10RegisterResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\aversion\x18\x03 \x01(\tR\aversion\x125\n" +
	"\x06routes\x18\x04 \x03(\v2\x1d.proto.RegisterResponse.RouteR\x06routes\x1aL\n" +
	"\x05Route\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x12\n" +
	"\x04path\x18\x02 \x01(\tR\x04path\x12\x17\n" +
	"\ause_sse\x18\x03 \x01(\bR\x06useSse\"\xac\x01\n" +
	"\x06Header\x121\n" +
	"\x06header\x18\x01 \x03(\v2\x19.proto.Header.HeaderEntryR\x06header\x1a\x1f\n" +
	"\x05Value\x12\x16\n" +
	"\x06values\x18\x01 \x03(\tR\x06values\x1aN\n" +
	"\vHeaderEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12)\n" +
	"\x05value\x18\x02 \x01(\v2\x13.proto.Header.ValueR\x05value:\x028\x01\"n\n" +
	"\aRequest\x12\x16\n" +
	"\x06method\x18\x01 \x01(\tR\x06method\x12\x10\n" +
	"\x03url\x18\x02 \x01(\tR\x03url\x12%\n" +
	"\x06header\x18\x03 \x01(\v2\r.proto.HeaderR\x06header\x12\x12\n" +
	"\x04body\x18\x04 \x01(\fR\x04body\"]\n" +
	"\bResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\x12%\n" +
	"\x06header\x18\x02 \x01(\v2\r.proto.HeaderR\x06header\x12\x12\n" +
	"\x04body\x18\x03 \x01(\tR\x04body2\xa0\x01\n" +
	"\x06Module\x12;\n" +
	"\bRegister\x12\x16.proto.RegisterRequest\x1a\x17.proto.RegisterResponse\x12)\n" +
	"\x06Handle\x12\x0e.proto.Request\x1a\x0f.proto.Response\x12.\n" +
	"\tHandleSSE\x12\x0e.proto.Request\x1a\x0f.proto.Response0\x01B\tZ\a./protob\x06proto3"

var (
	file_shared_proto_module_proto_rawDescOnce sync.Once
	file_shared_proto_module_proto_rawDescData []byte
)

func file_shared_proto_module_proto_rawDescGZIP() []byte {
	file_shared_proto_module_proto_rawDescOnce.Do(func() {
		file_shared_proto_module_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_shared_proto_module_proto_rawDesc), len(file_shared_proto_module_proto_rawDesc)))
	})
	return file_shared_proto_module_proto_rawDescData
}

var file_shared_proto_module_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_shared_proto_module_proto_goTypes = []any{
	(*Empty)(nil),                  // 0: proto.Empty
	(*RegisterRequest)(nil),        // 1: proto.RegisterRequest
	(*RegisterResponse)(nil),       // 2: proto.RegisterResponse
	(*Header)(nil),                 // 3: proto.Header
	(*Request)(nil),                // 4: proto.Request
	(*Response)(nil),               // 5: proto.Response
	(*RegisterResponse_Route)(nil), // 6: proto.RegisterResponse.Route
	(*Header_Value)(nil),           // 7: proto.Header.Value
	nil,                            // 8: proto.Header.HeaderEntry
}
var file_shared_proto_module_proto_depIdxs = []int32{
	6, // 0: proto.RegisterResponse.routes:type_name -> proto.RegisterResponse.Route
	8, // 1: proto.Header.header:type_name -> proto.Header.HeaderEntry
	3, // 2: proto.Request.header:type_name -> proto.Header
	3, // 3: proto.Response.header:type_name -> proto.Header
	7, // 4: proto.Header.HeaderEntry.value:type_name -> proto.Header.Value
	1, // 5: proto.Module.Register:input_type -> proto.RegisterRequest
	4, // 6: proto.Module.Handle:input_type -> proto.Request
	4, // 7: proto.Module.HandleSSE:input_type -> proto.Request
	2, // 8: proto.Module.Register:output_type -> proto.RegisterResponse
	5, // 9: proto.Module.Handle:output_type -> proto.Response
	5, // 10: proto.Module.HandleSSE:output_type -> proto.Response
	8, // [8:11] is the sub-list for method output_type
	5, // [5:8] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_shared_proto_module_proto_init() }
func file_shared_proto_module_proto_init() {
	if File_shared_proto_module_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_shared_proto_module_proto_rawDesc), len(file_shared_proto_module_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_shared_proto_module_proto_goTypes,
		DependencyIndexes: file_shared_proto_module_proto_depIdxs,
		MessageInfos:      file_shared_proto_module_proto_msgTypes,
	}.Build()
	File_shared_proto_module_proto = out.File
	file_shared_proto_module_proto_goTypes = nil
	file_shared_proto_module_proto_depIdxs = nil
}
